spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harshchoudhary56/config-store
          default-label: master  # Specify the branch (e.g., main, dev)
          clone-on-start: true
          username: harshchoudhary56
          password: ${GITHUB_TOKEN}
          refresh-rate: 30000  # Refresh every 30 seconds
          search-paths:
            - user_microservice
            - gateway
            - service_registry
    bus:
      id: ${spring.application.name}-${server.port}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: refresh,env,health,busrefresh
  endpoint:
    health:
      show-details: always
