spring:
  application:
  name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harshchoudhary56/config-store
          default-label: dev  # Specify the branch (e.g., main, dev)
          refresh-rate: 300 # Refresh every 5 minutes
          username: harshchoudhary56
          password: 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
          search-paths:
            - user_microservice/{profile}
            - gateway_microservice/{profile}
            - other_microservice/{profile}
server:
  port: 8888
